### ISSUE TITLE
Improve clang format

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#465]
They are multiple coding style rules that are not enforce by the clang format, it would be better if it was, if not, a coding style guide should be documented.

Initial suggestion by @snoyer about order of includes

```yaml
IncludeBlocks: Regroup
IncludeCategories:
  - Regex:           '".*"'
    Priority:        1
  - Regex:           '^<(vtk.*)>'
    Priority:        2
    CaseSensitive:   true
  # ... anything else ?
```
